name: Mary Carol Jennings
favicon: null
layout_spectrum: 0.7166783828288317
typography_spectrum: 0.8989904297050089
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.38591665495187044
  lightness: 0.9847250818274915
  saturation: 0.7260991032235324
  rhythmicContrast: 0.10758428880944848
purpose: []
