name: Mary Carol Jennings
favicon: null
layout_spectrum: 0.44217
typography_spectrum: 0.8284
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f9f9'
    - '#0a090d'
    - '#9eafcb'
    - '#354702'
    - '#71780a'
  brandStrength: 0.5
  lightness: 0.9375
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
